/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_PBEX_PBEX_TEST_PB_H_INCLUDED
#define PB_PBEX_PBEX_TEST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _pbex_Test1 {
    bool boolean;
    int32_t integral;
} pbex_Test1;

typedef struct _pbex_Test2 {
    bool boolean;
    int32_t integral;
    pb_callback_t string;
    pb_callback_t byteArray;
} pbex_Test2;

typedef struct _pbex_Test3 {
    pb_callback_t cb_body;
    pb_size_t which_body;
    union {
        pbex_Test1 item1;
        pbex_Test2 item2;
    } body;
} pbex_Test3;

typedef struct _pbex_Test4 {
    pb_callback_t item;
} pbex_Test4;

typedef struct _pbex_Test5 {
    pb_callback_t kv;
} pbex_Test5;

typedef struct _pbex_Test5_KvEntry {
    pb_callback_t key;
    int32_t value;
} pbex_Test5_KvEntry;

typedef struct _pbex_Test6 {
    pb_callback_t integrals;
} pbex_Test6;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define pbex_Test1_init_default                  {0, 0}
#define pbex_Test2_init_default                  {0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define pbex_Test3_init_default                  {{{NULL}, NULL}, 0, {pbex_Test1_init_default}}
#define pbex_Test4_init_default                  {{{NULL}, NULL}}
#define pbex_Test5_init_default                  {{{NULL}, NULL}}
#define pbex_Test5_KvEntry_init_default          {{{NULL}, NULL}, 0}
#define pbex_Test6_init_default                  {{{NULL}, NULL}}
#define pbex_Test1_init_zero                     {0, 0}
#define pbex_Test2_init_zero                     {0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define pbex_Test3_init_zero                     {{{NULL}, NULL}, 0, {pbex_Test1_init_zero}}
#define pbex_Test4_init_zero                     {{{NULL}, NULL}}
#define pbex_Test5_init_zero                     {{{NULL}, NULL}}
#define pbex_Test5_KvEntry_init_zero             {{{NULL}, NULL}, 0}
#define pbex_Test6_init_zero                     {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define pbex_Test1_boolean_tag                   1
#define pbex_Test1_integral_tag                  2
#define pbex_Test2_boolean_tag                   1
#define pbex_Test2_integral_tag                  2
#define pbex_Test2_string_tag                    3
#define pbex_Test2_byteArray_tag                 4
#define pbex_Test3_item1_tag                     1
#define pbex_Test3_item2_tag                     2
#define pbex_Test4_item_tag                      1
#define pbex_Test5_kv_tag                        1
#define pbex_Test5_KvEntry_key_tag               1
#define pbex_Test5_KvEntry_value_tag             2
#define pbex_Test6_integrals_tag                 1

/* Struct field encoding specification for nanopb */
#define pbex_Test1_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     boolean,           1) \
X(a, STATIC,   SINGULAR, INT32,    integral,          2)
#define pbex_Test1_CALLBACK NULL
#define pbex_Test1_DEFAULT NULL

#define pbex_Test2_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     boolean,           1) \
X(a, STATIC,   SINGULAR, INT32,    integral,          2) \
X(a, CALLBACK, SINGULAR, STRING,   string,            3) \
X(a, CALLBACK, SINGULAR, BYTES,    byteArray,         4)
#define pbex_Test2_CALLBACK pb_default_field_callback
#define pbex_Test2_DEFAULT NULL

#define pbex_Test3_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (body,item1,body.item1),   1) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (body,item2,body.item2),   2)
#define pbex_Test3_CALLBACK NULL
#define pbex_Test3_DEFAULT NULL
#define pbex_Test3_body_item1_MSGTYPE pbex_Test1
#define pbex_Test3_body_item2_MSGTYPE pbex_Test2

#define pbex_Test4_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  item,              1)
#define pbex_Test4_CALLBACK pb_default_field_callback
#define pbex_Test4_DEFAULT NULL
#define pbex_Test4_item_MSGTYPE pbex_Test1

#define pbex_Test5_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  kv,                1)
#define pbex_Test5_CALLBACK pb_default_field_callback
#define pbex_Test5_DEFAULT NULL
#define pbex_Test5_kv_MSGTYPE pbex_Test5_KvEntry

#define pbex_Test5_KvEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   SINGULAR, INT32,    value,             2)
#define pbex_Test5_KvEntry_CALLBACK pb_default_field_callback
#define pbex_Test5_KvEntry_DEFAULT NULL

#define pbex_Test6_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, INT32,    integrals,         1)
#define pbex_Test6_CALLBACK pb_default_field_callback
#define pbex_Test6_DEFAULT NULL

extern const pb_msgdesc_t pbex_Test1_msg;
extern const pb_msgdesc_t pbex_Test2_msg;
extern const pb_msgdesc_t pbex_Test3_msg;
extern const pb_msgdesc_t pbex_Test4_msg;
extern const pb_msgdesc_t pbex_Test5_msg;
extern const pb_msgdesc_t pbex_Test5_KvEntry_msg;
extern const pb_msgdesc_t pbex_Test6_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define pbex_Test1_fields &pbex_Test1_msg
#define pbex_Test2_fields &pbex_Test2_msg
#define pbex_Test3_fields &pbex_Test3_msg
#define pbex_Test4_fields &pbex_Test4_msg
#define pbex_Test5_fields &pbex_Test5_msg
#define pbex_Test5_KvEntry_fields &pbex_Test5_KvEntry_msg
#define pbex_Test6_fields &pbex_Test6_msg

/* Maximum encoded size of messages (where known) */
/* pbex_Test2_size depends on runtime parameters */
/* pbex_Test3_size depends on runtime parameters */
/* pbex_Test4_size depends on runtime parameters */
/* pbex_Test5_size depends on runtime parameters */
/* pbex_Test5_KvEntry_size depends on runtime parameters */
/* pbex_Test6_size depends on runtime parameters */
#define PBEX_PBEX_TEST_PB_H_MAX_SIZE             pbex_Test1_size
#define pbex_Test1_size                          13

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
