/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "pbex_test.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(pbex_Test1, pbex_Test1, AUTO)


PB_BIND(pbex_Test2, pbex_Test2, AUTO)


PB_BIND(pbex_Test3, pbex_Test3, AUTO)


PB_BIND(pbex_Test4, pbex_Test4, AUTO)


PB_BIND(pbex_Test5, pbex_Test5, AUTO)


PB_BIND(pbex_Test5_KvEntry, pbex_Test5_KvEntry, AUTO)


PB_BIND(pbex_Test6, pbex_Test6, AUTO)



